Add a test case.
jsmith1024/bill pull request #2
Opened 2022-02-12 14:29 UTC by jsmith1024

Created the bare skeleton of a test case.

2022-02-12 17:07 UTC, nekenyu requested changes
This will never compile.  Put in an example that should work.  It might be as simple as running a REPL over input without commands.

2022-02-12 21:36 UTC, jsmith1024 commented
This was an attempt to get the whole pull request figured out. Yes, pulll requests should be functional...

The point to making the evaluator an aggregated reference is: I can drop anything in there.

What I plan to do is drop a stub in there, which will echo back the input. If that makes sense to you, I can revise accordingly.

2022-02-12 22:53 UTC, nekenyu commented
That sounds fine.  Needs to be close to fictional than English sentences in a compiled code location.

Thank you,

 Jonathan

> On Feb 12, 2022, at 1:36 PM, Joe Smith ***@***.***> wrote:
> 
> ﻿
> Reopened #2.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you commented.

2022-02-13 00:56 UTC, nekenyu approved these changes

2022-02-13 00:57 UTC, merged