Update README.md
jsmith1024/bill pull request #9
Opened 2022-02-13 23:29 UTC by jsmith1024

2022-02-13 23:31 UTC, jsmith1024 reviewed
Trying to fix links, so page works.

2022-02-14 00:12 UTC, nekenyu requested changes

2022-02-14 00:12 UTC, nekenyu commented on README.md
> +- [Bill_Primer](langman/html/index.html)
In README.md, you want: https://jsmith1024.github.io/bill/langman/html/index.html

Note: README.md as rendered on github.com needs to link to the github page explicitly.  You might also update "Manuals:" to "Current Manuals:" or such.
This is different than what you want in the .dox pages which, when rendered use nice relative addresses.

2022-02-14 00:14 UTC, nekenyu approved these changes
Go ahead, try it....

2022-02-14 00:15 UTC, merged